ci: Move setting of docker image tag to a job with git

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -81,7 +81,13 @@ jobs:
       - name: Unit Tests
         run: |
           echo Running unit tests
-          # exit 1
+          # exit 1 # Fail test
+
+      - name: Set Docker Image Tag
+        run: |
+          branch=`git branch --show-current`
+          tag=$(echo $branch | tr / _)
+          echo "DOCKER_IMAGE_TAG=$tag" >> $GITHUB_ENV
 
       - name: Download Artifacts
         uses: actions/download-artifact@v2
@@ -116,11 +122,7 @@ jobs:
 
       - name: Build Docker Image
         if: ${{ success() }}
-        run: |
-          branch=`git branch --show-current`
-          tag=$(echo $branch | tr / _)
-          echo "DOCKER_IMAGE_TAG=$tag" >> $GITHUB_ENV
-          docker build --tag ${{ env.DOCKER_IMAGE }}:$tag .
+        run: docker build --tag ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} .
 
       - name: Publish Docker Image
         if: ${{ success() }}
